{{ config(materialized='table') }}
select distinct 
LOCATION,
ISLAND,
TOTAL_CASES,
TOTAL_RECOVERED,
TOTAL_CASES_PER_MILLION,
TOTAL_ACTIVE_CASES,
NEW_CASES_PER_MILLION,
NEW_DEATHS_PER_MILLION,
NEW_RECOVERED,
CASE_FATALITY_RATE,
NEW_DEATHS,
CASE_RECOVERED_RATE,
NEW_CASES,
TOTAL_DEATHS,
DATE,
GROWTH_FACTOR_OF_NEW_DEATHS,
GROWTH_FACTOR_OF_NEW_CASES,
POPULATION
from "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_NAVANEETHKUMAR_MADUGULA"
