{{ config(materialized='table') }}
select distinct 
TOTAL_CITIES,
TOTAL_DISTRICTS,
TOTAL_REGENCIES,
POPULATION_DENSITY,
TOTAL_RURAL_VILLAGES,
"POPULATION"
from "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_NAVANEETHKUMAR_MADUGULA"
